x-common-environments: &common-environments
  TZ: Asia/Bangkok
  LANG: C.UTF-8
  LANG_ALL: C.UTF-8

services:
  traefik:
    image: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
      - "--entrypoints.web_8080.address=:8080"
      - "--entrypoints.web_8443.address=:8443"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  user:
    depends_on:
      traefik:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: air.Dockerfile
    environment:
      <<: *common-environments
      RUN_ENV: "dev"
    command: ["air", "-c", "user.air.toml"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/api/v1/users/`)"
      - "traefik.http.routers.user.entrypoints=web_8080"
      - "traefik.http.routers.user.service=user"
      - "traefik.http.services.user.loadbalancer.server.port=8080"
    volumes:
      - .:/app

  auth:
    depends_on:
      user:
        condition: service_started
      traefik:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: air.Dockerfile
    environment:
      <<: *common-environments
      RUN_ENV: "dev"
    command: ["air", "-c", "auth.air.toml"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/v1/auth/`)"
      - "traefik.http.routers.auth.entrypoints=web_8080"
      - "traefik.http.routers.auth.service=auth"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
    volumes:
      - .:/app

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    volumes:
      - ./tmp/dragonfly-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres
    environment:
      <<: *common-environments
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  dbgate:
    depends_on:
      traefik:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: dbgate/dbgate
    environment:
      <<: *common-environments
    volumes:
      - ./tmp/dbgate-data:/root/.dbgate
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbgate.rule=Host(`dbgate.localhost`)"
      - "traefik.http.routers.dbgate.entrypoints=web_8080"
      - "traefik.http.routers.dbgate.service=dbgate"
      - "traefik.http.services.dbgate.loadbalancer.server.port=3000"
