// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: pkg/proto/user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserAccountService_CreateUserAccount_FullMethodName = "/user.UserAccountService/CreateUserAccount"
	UserAccountService_ReadUserAccount_FullMethodName   = "/user.UserAccountService/ReadUserAccount"
	UserAccountService_UpdateUserAccount_FullMethodName = "/user.UserAccountService/UpdateUserAccount"
	UserAccountService_DeleteUserAccount_FullMethodName = "/user.UserAccountService/DeleteUserAccount"
)

// UserAccountServiceClient is the client API for UserAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAccountServiceClient interface {
	CreateUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error)
	ReadUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error)
	UpdateUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error)
	DeleteUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error)
}

type userAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAccountServiceClient(cc grpc.ClientConnInterface) UserAccountServiceClient {
	return &userAccountServiceClient{cc}
}

func (c *userAccountServiceClient) CreateUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error) {
	out := new(UserAccount)
	err := c.cc.Invoke(ctx, UserAccountService_CreateUserAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountServiceClient) ReadUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error) {
	out := new(UserAccount)
	err := c.cc.Invoke(ctx, UserAccountService_ReadUserAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountServiceClient) UpdateUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error) {
	out := new(UserAccount)
	err := c.cc.Invoke(ctx, UserAccountService_UpdateUserAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountServiceClient) DeleteUserAccount(ctx context.Context, in *UserAccount, opts ...grpc.CallOption) (*UserAccount, error) {
	out := new(UserAccount)
	err := c.cc.Invoke(ctx, UserAccountService_DeleteUserAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAccountServiceServer is the server API for UserAccountService service.
// All implementations must embed UnimplementedUserAccountServiceServer
// for forward compatibility
type UserAccountServiceServer interface {
	CreateUserAccount(context.Context, *UserAccount) (*UserAccount, error)
	ReadUserAccount(context.Context, *UserAccount) (*UserAccount, error)
	UpdateUserAccount(context.Context, *UserAccount) (*UserAccount, error)
	DeleteUserAccount(context.Context, *UserAccount) (*UserAccount, error)
	mustEmbedUnimplementedUserAccountServiceServer()
}

// UnimplementedUserAccountServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserAccountServiceServer struct {
}

func (UnimplementedUserAccountServiceServer) CreateUserAccount(context.Context, *UserAccount) (*UserAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAccount not implemented")
}
func (UnimplementedUserAccountServiceServer) ReadUserAccount(context.Context, *UserAccount) (*UserAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUserAccount not implemented")
}
func (UnimplementedUserAccountServiceServer) UpdateUserAccount(context.Context, *UserAccount) (*UserAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAccount not implemented")
}
func (UnimplementedUserAccountServiceServer) DeleteUserAccount(context.Context, *UserAccount) (*UserAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAccount not implemented")
}
func (UnimplementedUserAccountServiceServer) mustEmbedUnimplementedUserAccountServiceServer() {}

// UnsafeUserAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAccountServiceServer will
// result in compilation errors.
type UnsafeUserAccountServiceServer interface {
	mustEmbedUnimplementedUserAccountServiceServer()
}

func RegisterUserAccountServiceServer(s grpc.ServiceRegistrar, srv UserAccountServiceServer) {
	s.RegisterService(&UserAccountService_ServiceDesc, srv)
}

func _UserAccountService_CreateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountServiceServer).CreateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountService_CreateUserAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountServiceServer).CreateUserAccount(ctx, req.(*UserAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountService_ReadUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountServiceServer).ReadUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountService_ReadUserAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountServiceServer).ReadUserAccount(ctx, req.(*UserAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountService_UpdateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountServiceServer).UpdateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountService_UpdateUserAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountServiceServer).UpdateUserAccount(ctx, req.(*UserAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountService_DeleteUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountServiceServer).DeleteUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountService_DeleteUserAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountServiceServer).DeleteUserAccount(ctx, req.(*UserAccount))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAccountService_ServiceDesc is the grpc.ServiceDesc for UserAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserAccountService",
	HandlerType: (*UserAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserAccount",
			Handler:    _UserAccountService_CreateUserAccount_Handler,
		},
		{
			MethodName: "ReadUserAccount",
			Handler:    _UserAccountService_ReadUserAccount_Handler,
		},
		{
			MethodName: "UpdateUserAccount",
			Handler:    _UserAccountService_UpdateUserAccount_Handler,
		},
		{
			MethodName: "DeleteUserAccount",
			Handler:    _UserAccountService_DeleteUserAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/user/user.proto",
}

const (
	UserProfileService_CreateUserProfile_FullMethodName = "/user.UserProfileService/CreateUserProfile"
	UserProfileService_ReadUserProfile_FullMethodName   = "/user.UserProfileService/ReadUserProfile"
	UserProfileService_UpdateUserProfile_FullMethodName = "/user.UserProfileService/UpdateUserProfile"
	UserProfileService_DeleteUserProfile_FullMethodName = "/user.UserProfileService/DeleteUserProfile"
)

// UserProfileServiceClient is the client API for UserProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserProfileServiceClient interface {
	CreateUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error)
	ReadUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error)
	UpdateUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error)
	DeleteUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error)
}

type userProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserProfileServiceClient(cc grpc.ClientConnInterface) UserProfileServiceClient {
	return &userProfileServiceClient{cc}
}

func (c *userProfileServiceClient) CreateUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, UserProfileService_CreateUserProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) ReadUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, UserProfileService_ReadUserProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) UpdateUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, UserProfileService_UpdateUserProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) DeleteUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, UserProfileService_DeleteUserProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfileServiceServer is the server API for UserProfileService service.
// All implementations must embed UnimplementedUserProfileServiceServer
// for forward compatibility
type UserProfileServiceServer interface {
	CreateUserProfile(context.Context, *UserProfile) (*UserProfile, error)
	ReadUserProfile(context.Context, *UserProfile) (*UserProfile, error)
	UpdateUserProfile(context.Context, *UserProfile) (*UserProfile, error)
	DeleteUserProfile(context.Context, *UserProfile) (*UserProfile, error)
	mustEmbedUnimplementedUserProfileServiceServer()
}

// UnimplementedUserProfileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserProfileServiceServer struct {
}

func (UnimplementedUserProfileServiceServer) CreateUserProfile(context.Context, *UserProfile) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserProfile not implemented")
}
func (UnimplementedUserProfileServiceServer) ReadUserProfile(context.Context, *UserProfile) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUserProfile not implemented")
}
func (UnimplementedUserProfileServiceServer) UpdateUserProfile(context.Context, *UserProfile) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (UnimplementedUserProfileServiceServer) DeleteUserProfile(context.Context, *UserProfile) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserProfile not implemented")
}
func (UnimplementedUserProfileServiceServer) mustEmbedUnimplementedUserProfileServiceServer() {}

// UnsafeUserProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserProfileServiceServer will
// result in compilation errors.
type UnsafeUserProfileServiceServer interface {
	mustEmbedUnimplementedUserProfileServiceServer()
}

func RegisterUserProfileServiceServer(s grpc.ServiceRegistrar, srv UserProfileServiceServer) {
	s.RegisterService(&UserProfileService_ServiceDesc, srv)
}

func _UserProfileService_CreateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).CreateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileService_CreateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).CreateUserProfile(ctx, req.(*UserProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_ReadUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).ReadUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileService_ReadUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).ReadUserProfile(ctx, req.(*UserProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileService_UpdateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).UpdateUserProfile(ctx, req.(*UserProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_DeleteUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).DeleteUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProfileService_DeleteUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).DeleteUserProfile(ctx, req.(*UserProfile))
	}
	return interceptor(ctx, in, info, handler)
}

// UserProfileService_ServiceDesc is the grpc.ServiceDesc for UserProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserProfileService",
	HandlerType: (*UserProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserProfile",
			Handler:    _UserProfileService_CreateUserProfile_Handler,
		},
		{
			MethodName: "ReadUserProfile",
			Handler:    _UserProfileService_ReadUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _UserProfileService_UpdateUserProfile_Handler,
		},
		{
			MethodName: "DeleteUserProfile",
			Handler:    _UserProfileService_DeleteUserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/user/user.proto",
}

const (
	UserAddressService_CreateUserAddress_FullMethodName = "/user.UserAddressService/CreateUserAddress"
	UserAddressService_ReadUserAddress_FullMethodName   = "/user.UserAddressService/ReadUserAddress"
	UserAddressService_UpdateUserAddress_FullMethodName = "/user.UserAddressService/UpdateUserAddress"
	UserAddressService_DeleteUserAddress_FullMethodName = "/user.UserAddressService/DeleteUserAddress"
)

// UserAddressServiceClient is the client API for UserAddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAddressServiceClient interface {
	CreateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error)
	ReadUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error)
	UpdateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error)
	DeleteUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error)
}

type userAddressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAddressServiceClient(cc grpc.ClientConnInterface) UserAddressServiceClient {
	return &userAddressServiceClient{cc}
}

func (c *userAddressServiceClient) CreateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error) {
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserAddressService_CreateUserAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddressServiceClient) ReadUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error) {
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserAddressService_ReadUserAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddressServiceClient) UpdateUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error) {
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserAddressService_UpdateUserAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddressServiceClient) DeleteUserAddress(ctx context.Context, in *UserAddress, opts ...grpc.CallOption) (*UserAddress, error) {
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserAddressService_DeleteUserAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAddressServiceServer is the server API for UserAddressService service.
// All implementations must embed UnimplementedUserAddressServiceServer
// for forward compatibility
type UserAddressServiceServer interface {
	CreateUserAddress(context.Context, *UserAddress) (*UserAddress, error)
	ReadUserAddress(context.Context, *UserAddress) (*UserAddress, error)
	UpdateUserAddress(context.Context, *UserAddress) (*UserAddress, error)
	DeleteUserAddress(context.Context, *UserAddress) (*UserAddress, error)
	mustEmbedUnimplementedUserAddressServiceServer()
}

// UnimplementedUserAddressServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserAddressServiceServer struct {
}

func (UnimplementedUserAddressServiceServer) CreateUserAddress(context.Context, *UserAddress) (*UserAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAddress not implemented")
}
func (UnimplementedUserAddressServiceServer) ReadUserAddress(context.Context, *UserAddress) (*UserAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUserAddress not implemented")
}
func (UnimplementedUserAddressServiceServer) UpdateUserAddress(context.Context, *UserAddress) (*UserAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAddress not implemented")
}
func (UnimplementedUserAddressServiceServer) DeleteUserAddress(context.Context, *UserAddress) (*UserAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserAddress not implemented")
}
func (UnimplementedUserAddressServiceServer) mustEmbedUnimplementedUserAddressServiceServer() {}

// UnsafeUserAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAddressServiceServer will
// result in compilation errors.
type UnsafeUserAddressServiceServer interface {
	mustEmbedUnimplementedUserAddressServiceServer()
}

func RegisterUserAddressServiceServer(s grpc.ServiceRegistrar, srv UserAddressServiceServer) {
	s.RegisterService(&UserAddressService_ServiceDesc, srv)
}

func _UserAddressService_CreateUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddressServiceServer).CreateUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAddressService_CreateUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddressServiceServer).CreateUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddressService_ReadUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddressServiceServer).ReadUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAddressService_ReadUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddressServiceServer).ReadUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddressService_UpdateUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddressServiceServer).UpdateUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAddressService_UpdateUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddressServiceServer).UpdateUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddressService_DeleteUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddressServiceServer).DeleteUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAddressService_DeleteUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddressServiceServer).DeleteUserAddress(ctx, req.(*UserAddress))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAddressService_ServiceDesc is the grpc.ServiceDesc for UserAddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserAddressService",
	HandlerType: (*UserAddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserAddress",
			Handler:    _UserAddressService_CreateUserAddress_Handler,
		},
		{
			MethodName: "ReadUserAddress",
			Handler:    _UserAddressService_ReadUserAddress_Handler,
		},
		{
			MethodName: "UpdateUserAddress",
			Handler:    _UserAddressService_UpdateUserAddress_Handler,
		},
		{
			MethodName: "DeleteUserAddress",
			Handler:    _UserAddressService_DeleteUserAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/user/user.proto",
}

const (
	UserDetailsService_ReadUserDetails_FullMethodName = "/user.UserDetailsService/ReadUserDetails"
)

// UserDetailsServiceClient is the client API for UserDetailsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserDetailsServiceClient interface {
	ReadUserDetails(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (*UserDetails, error)
}

type userDetailsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDetailsServiceClient(cc grpc.ClientConnInterface) UserDetailsServiceClient {
	return &userDetailsServiceClient{cc}
}

func (c *userDetailsServiceClient) ReadUserDetails(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (*UserDetails, error) {
	out := new(UserDetails)
	err := c.cc.Invoke(ctx, UserDetailsService_ReadUserDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDetailsServiceServer is the server API for UserDetailsService service.
// All implementations must embed UnimplementedUserDetailsServiceServer
// for forward compatibility
type UserDetailsServiceServer interface {
	ReadUserDetails(context.Context, *UserDetails) (*UserDetails, error)
	mustEmbedUnimplementedUserDetailsServiceServer()
}

// UnimplementedUserDetailsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserDetailsServiceServer struct {
}

func (UnimplementedUserDetailsServiceServer) ReadUserDetails(context.Context, *UserDetails) (*UserDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUserDetails not implemented")
}
func (UnimplementedUserDetailsServiceServer) mustEmbedUnimplementedUserDetailsServiceServer() {}

// UnsafeUserDetailsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDetailsServiceServer will
// result in compilation errors.
type UnsafeUserDetailsServiceServer interface {
	mustEmbedUnimplementedUserDetailsServiceServer()
}

func RegisterUserDetailsServiceServer(s grpc.ServiceRegistrar, srv UserDetailsServiceServer) {
	s.RegisterService(&UserDetailsService_ServiceDesc, srv)
}

func _UserDetailsService_ReadUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsServiceServer).ReadUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDetailsService_ReadUserDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsServiceServer).ReadUserDetails(ctx, req.(*UserDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// UserDetailsService_ServiceDesc is the grpc.ServiceDesc for UserDetailsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDetailsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserDetailsService",
	HandlerType: (*UserDetailsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadUserDetails",
			Handler:    _UserDetailsService_ReadUserDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/user/user.proto",
}
