[app]
env = "dev"
debug = true
listen = "0.0.0.0"
automigrate = true
[app.port]
http = 8080
grpc = 8443

[jwt]
key = "your-secret-key"
ttl = "8h"

[db]
[db.postgres]
host = "postgres"
port = 5432
user = "postgres"
password = "postgres"
database = "postgres"

[db.redis]
host = "redis"
port = 6379
password = ""
database = 0
